version: 2.1
orbs:
  node: circleci/node@7.1.0
jobs:
  build-and-test:
    docker:
      - image: "cimg/base:stable"
      - image: mongo:5.0
        name: mongo
        ports: 
          - "27017:27017"
        environment:
          MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
          MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    steps:
      - checkout
      - node/install
      - node/install-packages
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Attendre que MongoDB démarre
          command: |
            for i in `seq 1 10`; do
              nc -z localhost 27017 && echo "MongoDB est prêt" && break
              echo "En attente de MongoDB..."
              sleep 3
            done
      - run:
          name: Construire un conteneur pour tester la connexion
          command: |
            mongo "$DATABASE_URL" --eval "db.runCommand({ ping: 1 })"
workflows:
  build-and-test:
    jobs:
      - build-and-test:
        matrix:
            parameters:
              node-version: [19.x, 20.x, 21.x, 22.x]