version: 2.1
orbs:
  node: circleci/node@7.1.0
jobs:
  build-and-test:
    docker:
      - image: "cimg/base:stable"
    mongodb:
      - image: mongo:5.0
        name: mongo
        ports: 
          - "27017:27017"
        environment:
          MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
          MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - node/install
      - node/install-packages
      - run:
          name: Run Linter
          command: npm run lint
      - run:
          name: Run type-check
          command: npm run type-check
      - run:
          name: MongoDB Install
          command: |
            sudo apt-get install -y mongodb
      - run:
          name: Wait MongoDB to start...
          command: |
            for i in `seq 1 10`; do
              nc -z localhost 27017 && echo "MongoDB is ready" && break
              echo "Waiting MongoDB connection..."
              sleep 3
            done
      - run:
          name: Run tests
          command: npm run test
workflows:
  build-and-test:
    jobs:
      - build-and-test:
        matrix:
            parameters:
              node-version: [19.x, 20.x, 21.x, 22.x]