version: 2.1
orbs:
  node: circleci/node@7.1.0
jobs:
  build-and-test:
    docker:
      - image: "cimg/base:stable"
      - image: mongo:5.0
        name: mongo
        environment:
          MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
          MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    steps:
      - checkout
      - node/install
      - node/install-packages
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Construire un conteneur pour tester la connexion
          command: |
            echo 'FROM mongo:5.0
            CMD mongo "$DATABASE_URL" --eval "db.runCommand({ ping: 1 })"
            ' > Dockerfile
            docker build -t mongo-conn-check .
            docker run --network host mongo-conn-check
workflows:
  build-and-test:
    jobs:
      - build-and-test:
        matrix:
            parameters:
              node-version: [19.x, 20.x, 21.x, 22.x]