version: 2.1
orbs:
  node: circleci/node@7.1.0
jobs:
  build-and-test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install
      - node/install-packages
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Test remote MongoDB connection
          command: |
            apt-get update && apt-get install -y mongodb-clients
            mongo "$DATABASE_URL" --eval 'db.runCommand({ ping: 1 })'
workflows:
  build-and-test:
    jobs:
      - build-and-test:
        matrix:
            parameters:
              node-version: [19.x, 20.x, 21.x, 22.x]